# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c64296996eb8397724e60c482619b9b74f32c762c27830631205c20dd5dd5614c7760946d9b9b589f3c1ff1c23be2f6dae8ccb016f6bafe87c88d765a30675c

test:
  secret_key_base: a4facce54ed1cc5a079d9291167b9a34ac400ae883aca521b4c807284b3aff80705e28c41f1e75b71483da83bd17bbd8c09d00e77053a4037dd2dab9cb8b9d08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
